# Generated by Django 4.2.13 on 2025-05-27 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category (e.g., Chandeliers, Furniture).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the category.', null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the tag (e.g., New Arrival, Clearance).', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A detailed description of the product.', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='The selling price of the product.', max_digits=10)),
                ('quantity', models.IntegerField(default=0, help_text='The current stock quantity of the product.')),
                ('item_code', models.CharField(help_text='A unique code for identifying the product.', max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, help_text='An image of the product.', null=True, upload_to='product_photos/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('out_of_stock', 'Out of Stock')], default='available', help_text='The current availability status of the product.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='The category this product belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='Select relevant tags for this product.', to='inventory.tag')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
