# Generated by Django 4.2.13 on 2025-05-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='A unique identifier for the invoice.', max_length=100, unique=True)),
                ('customer_name', models.CharField(help_text='The name of the customer for this invoice.', max_length=255)),
                ('customer_email', models.EmailField(blank=True, help_text="The customer's email address.", max_length=254, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='The total amount of the invoice.', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', help_text='The current status of the invoice.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='The quantity of the product in this invoice item.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='The price of the product at the time of invoicing.', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated as quantity * unit_price.', max_digits=10)),
                ('invoice', models.ForeignKey(help_text='The invoice this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.invoice')),
                ('product', models.ForeignKey(blank=True, help_text='The product being invoiced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['id'],
                'unique_together': {('invoice', 'product')},
            },
        ),
    ]
