# Generated by Django 4.2.13 on 2025-05-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_invoice_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount applied to the total invoice amount (e.g., 10.00 for $10 discount).', max_digits=10),
        ),
    ]
