# Generated by Django 4.2.13 on 2025-05-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_invoice_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_email',
        ),
        migrations.AddField(
            model_name='invoice',
            name='home_address',
            field=models.TextField(blank=True, help_text="The customer's home address.", null=True),
        ),
    ]
