# Generated by Django 4.2.13 on 2025-05-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_color_product_measurements_cm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the size (e.g., Small, Medium, Large, XL, 32, 100cm).', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='product',
            name='measurements_cm',
            field=models.CharField(blank=True, help_text="Measurements of the product in CM (e.g., '10x5x2 cm' or 'Diameter: 15cm').", max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, help_text='Select available sizes for this product.', to='inventory.size'),
        ),
    ]
