# Generated by Django 4.2.13 on 2025-05-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_size_remove_product_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Products that have this size.', related_name='sizes_reverse', to='inventory.product'),
        ),
    ]
