# Generated by Django 4.2.13 on 2025-06-01 01:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_size_products'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(default='', help_text='The name of the product at the time of invoicing (stored for historical accuracy).', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, help_text='A unique identifier for the invoice.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The total amount of the invoice after discount. Calculated automatically.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The product being invoiced (can be null if product deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='The quantity of the product in this invoice item.'),
        ),
    ]
