# Generated by Django 5.2.1 on 2025-06-01 02:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_invoiceitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='The total amount of the invoice after discount. Calculated automatically.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(editable=False, help_text='The name of the product at the time of invoicing (stored for historical accuracy).', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculated as quantity * unit_price.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(help_text='The name of the size (e.g., 40cm,50cm,60cm,80cm,90cm,100cm).', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Products that have this size.', related_name='sizes', to='inventory.product'),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together={('invoice', 'product')},
        ),
    ]
