# Generated by Django 5.2.1 on 2025-06-01 02:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_invoice_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The amount paid by the customer for this invoice.', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='The remaining balance for this invoice.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('uncompleted', 'Uncompleted'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', help_text='The current status of the invoice.', max_length=20),
        ),
    ]
