# Generated by Django 5.2.1 on 2025-06-03 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_invoice_amount_paid_invoice_amount_remaining_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user who last modified this invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
