# Generated by Django 5.2.1 on 2025-06-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The cost price of the product (for calculating profit).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, help_text='Select available sizes for this product.', related_name='products_with_this_size', to='inventory.size'),
        ),
    ]
