# Generated by Django 5.2.1 on 2025-06-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_size_products_product_cost_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='The date by which the invoice amount is due.', null=True),
        ),
    ]
