# Generated by Django 5.2.1 on 2025-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_invoice_manager_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('visa', 'Visa'), ('fawry', 'Fawry'), ('instapay', 'InstaPay')], help_text='Method of payment.', max_length=50, null=True),
        ),
    ]
