# Generated by Django 4.2.13 on 2025-06-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_address',
            field=models.CharField(blank=True, help_text='Optional company/branch address for this invoice.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(help_text='The name of the product at the time of invoicing (stored for historical accuracy).', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='The quantity of the item.'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='The price per unit of this item', max_digits=10),
        ),
    ]
