# Generated by Django 4.2.13 on 2025-06-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_invoiceitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company_phone',
            field=models.CharField(default='01065881729 - 01126905990 - 01110001559', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_address',
            field=models.CharField(default='FPI, Damietta Furniture Point Mall', max_length=255),
        ),
    ]
