# Generated by Django 4.2.13 on 2025-06-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_invoice_company_phone_alter_invoice_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
