# Generated by Django 4.2.13 on 2025-06-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_invoiceitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
