# Generated by Django 4.2.13 on 2025-06-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_invoice_token_invoice_token_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='secure_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
