# Generated by Django 4.2.13 on 2025-06-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_invoice_secure_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='secure_token',
        ),
    ]
