# Generated by Django 4.2.13 on 2025-07-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_invoice_secure_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cloud_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_address',
            field=models.CharField(blank=True, default='FPI, Damietta Furniture Point Mall', help_text='Optional company/branch address for this invoice.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_phone',
            field=models.CharField(blank=True, default='01065881729 - 01126905990 - 01110001559', help_text='Optional company phone number for this invoice.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('visa', 'Visa'), ('instapay', 'InstaPay')], help_text='Method of payment.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
