# Generated by Django 4.2.13 on 2025-08-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_invoice_cloud_pdf_url_alter_invoice_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measurements_cm',
        ),
        migrations.AddField(
            model_name='product',
            name='measurements',
            field=models.CharField(blank=True, help_text="Measurements of the product in CM (e.g., '12 LAMP' or 'Diameter: 15cm').", max_length=255, null=True),
        ),
    ]
