# Generated by Django 4.2.13 on 2025-08-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_remove_product_measurements_cm_product_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='include_product_photos',
            field=models.BooleanField(default=False, help_text='Include product photos in the invoice PDF.'),
        ),
    ]
