# Generated by Django 4.2.13 on 2025-08-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_invoice_include_product_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='show_product_photos',
            field=models.BooleanField(default=False),
        ),
    ]
