# Generated by Django 4.2.13 on 2025-08-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_invoice_show_product_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='include_product_photos',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='show_product_photos',
            field=models.BooleanField(default=False, help_text='show product photos in the invoice PDF.'),
        ),
    ]
