# Generated by Django 4.2.13 on 2025-08-10 00:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_remove_invoice_include_product_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='The sum of all items. Calculated automatically.', max_digits=10),
        ),
    ]
