"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
from django.utils.translation import gettext_lazy as _



BASE_URL = "http://127.0.0.1:8000"


load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# You should generate a strong, random key for production.
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-your-very-secret-key-here-1234567890abcdef')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# NEVER USE '*' IN PRODUCTION FOR SECURITY REASONS.
# This setting tells Django to allow requests from any host.
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'inventory', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reports',
    'rest_framework',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 os.path.join(BASE_DIR, 'django_project', 'templates'),],
        'APP_DIRS': True, # This must be True
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n', 
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
import os

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'lazordydb',
        'USER': 'postgres',
        'PASSWORD': 'venom66samir+d',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('ar', 'العربية'), 
    ('en', 'English'),  
]
TIME_ZONE = 'Africa/Cairo'

USE_I18N = True
USE_L10N = True
USE_TZ = True



LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    
    os.path.join(BASE_DIR, 'inventory', 'static'),
      
]
STATIC_ROOT = os.path.join(
    BASE_DIR,
    'staticfiles',)  # Where 'collectstatic' will gather all static files

# Media files (for user-uploaded content like product photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,
                           'media')  # Where user-uploaded files will be stored

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Add CSRF Trusted Origins for dynamic URLs
# This is crucial for environments behind proxies that might
# interfere with the Origin header.
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]


# jazzmin dark theme settings
JAZZMIN_SETTINGS = {
    "site_title": "Lazordy Inventory",
    "site_header": "Lazordy Admin",
    "site_brand": "Lazordy",
    "site_logo": "lazordy_theme/img/lazordy_logo.png",  # Make sure this path is correct
    "welcome_sign": "Welcome to Lazordy Admin",
    "copyright": "© 2025 Lazordy",
    "custom_css": "lazordy_theme/css/admin_dark_mode_fix.css",  
}


LOGIN_REDIRECT_URL = '/inventory/'


CLOUDINARY = {
    'cloud_name': 'dkeopupxb',
    'api_key': '814938212617526',
    'api_secret': 'VRnq0HKU8uS8y0gG6nCTsrY1tt0',
}
