"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os  # Import the os module

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# You should generate a strong, random key for production.
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-your-very-secret-key-here-1234567890abcdef')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# DANGER! THIS IS FOR DEVELOPMENT DEBUGGING ON  ONLY!
# NEVER USE '*' IN PRODUCTION FOR SECURITY REASONS.
# This setting tells Django to allow requests from any host.
ALLOWED_HOSTS = [
    '*',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory',  
    'rest_framework', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static', # This is a common place for project-wide static files
    # BASE_DIR / 'inventory' / 'static', # You can optionally add this if your app's static is not found via BASE_DIR / 'static'
]
STATIC_ROOT = os.path.join(
    BASE_DIR,
    'staticfiles')  # Where 'collectstatic' will gather all static files

# Media files (for user-uploaded content like product photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,
                          'media')  # Where user-uploaded files will be stored

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#  Specific (might be needed for some  setups for Django Admin JS)
# This usually only applies when DEBUG=False, but sometimes helps with  proxy
# if not explicitly handling static files. For now, keep it simple.
# You don't usually need to modify URL_PREFIX for Django unless using specific proxy setups.
# If you run into issues with static files not loading (404s), revisit this.
# For DEBUG=True, runserver handles static files automatically.
# django_project/settings.py

# ... (your existing settings) ...

# DANGER! THIS IS FOR DEVELOPMENT DEBUGGING ON  ONLY!
# NEVER USE '*' IN PRODUCTION FOR SECURITY REASONS.
ALLOWED_HOSTS = [
    '*',  # Keep this as it is for now
]

# Add CSRF Trusted Origins for  dynamic URLs
# This is crucial for environments behind proxies that might
# interfere with the Origin header.
CSRF_TRUSTED_ORIGINS = [
    'https://2e484a9a-461e-4e1d-81ea-544a49533b23-00-yvybadytzint.kirk.replit.dev',  # Your exact  URL
    'https://*.replit.dev',  # General wildcard for  URLs
    'https://*.*.replit.dev',  # More general pattern for multi-level  subdomains
    'https://*.*.*.replit.dev',  # Even more general
]


# Media files (for user-uploaded content like product photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' # This creates a 'media' directory in your project root